/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemrograman_komputer_sem4_tugas_1_aplikasi_desktop;

/**
 *
 * @author fadil
 */
public class main extends javax.swing.JFrame {

    private double hasil = 0;
    private String operasi = "";
    private boolean baru = true;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_satu = new javax.swing.JButton();
        btn_dua = new javax.swing.JButton();
        btn_tiga = new javax.swing.JButton();
        btn_menjadikan_plus_atau_minus = new javax.swing.JButton();
        btn_persen = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_enam = new javax.swing.JButton();
        btn_lima = new javax.swing.JButton();
        btn_empat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_delapan = new javax.swing.JButton();
        btn_sembilan = new javax.swing.JButton();
        btn_tujuh = new javax.swing.JButton();
        btn_kali = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_bagi = new javax.swing.JButton();
        btn_kurang = new javax.swing.JButton();
        btn_koma = new javax.swing.JButton();
        btn_samadengan = new javax.swing.JButton();
        btn_nol = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Simple Calculator.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        btn_satu.setText("1");
        btn_satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_satuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_satu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 55, 55));

        btn_dua.setText("2");
        btn_dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_duaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 55, 55));

        btn_tiga.setText("3");
        btn_tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tigaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 55, 55));

        btn_menjadikan_plus_atau_minus.setText("+/-");
        btn_menjadikan_plus_atau_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menjadikan_plus_atau_minusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menjadikan_plus_atau_minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 55, 55));

        btn_persen.setText("%");
        btn_persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_persenActionPerformed(evt);
            }
        });
        getContentPane().add(btn_persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 55, 55));

        btn_reset.setText("AC");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 55, 55));

        btn_enam.setText("6");
        btn_enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enamActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 55, 55));

        btn_lima.setText("5");
        btn_lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lima, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 55, 55));

        btn_empat.setText("4");
        btn_empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_empat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 55, 55));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel2.setText("0");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btn_delapan.setText("8");
        btn_delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delapanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 55, 55));

        btn_sembilan.setText("9");
        btn_sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sembilanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sembilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 55, 55));

        btn_tujuh.setText("7");
        btn_tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tujuhActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 55, 55));

        btn_kali.setText("x");
        btn_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 55, 55));

        btn_tambah.setText("+");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 55, 55));

        btn_bagi.setText(":");
        btn_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bagiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 55, 55));

        btn_kurang.setText("-");
        btn_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kurangActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 55, 55));

        btn_koma.setText("1");
        btn_koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_komaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_koma, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 55, 55));

        btn_samadengan.setText("=");
        btn_samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_samadenganActionPerformed(evt);
            }
        });
        getContentPane().add(btn_samadengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 55, 55));

        btn_nol.setText("0");
        btn_nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nolActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 128, 55));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_satuActionPerformed
        // TODO add your handling code here:
        tambahAngka("1");
    }//GEN-LAST:event_btn_satuActionPerformed

    private void btn_duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_duaActionPerformed
        // TODO add your handling code here:
        tambahAngka("2");
    }//GEN-LAST:event_btn_duaActionPerformed

    private void btn_tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tigaActionPerformed
        // TODO add your handling code here:
        tambahAngka("3");

    }//GEN-LAST:event_btn_tigaActionPerformed

    private void btn_menjadikan_plus_atau_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menjadikan_plus_atau_minusActionPerformed
        // TODO add your handling code here:
        String teks = jLabel2.getText();
        if (!teks.isEmpty()) {
            double angka = Double.parseDouble(teks);
            jLabel2.setText(String.valueOf(-angka));
        }


    }//GEN-LAST:event_btn_menjadikan_plus_atau_minusActionPerformed

    private void btn_persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_persenActionPerformed
        // TODO add your handling code here:
        String teks = jLabel2.getText();
        if (!teks.isEmpty()) {
            double angka = Double.parseDouble(teks);
            jLabel2.setText(String.valueOf(angka / 100));
        }
    }//GEN-LAST:event_btn_persenActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        jLabel2.setText("0");
        hasil = 0;
        operasi = "";
        baru = true;
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enamActionPerformed
        // TODO add your handling code here:tambahAngka
        tambahAngka("6");


    }//GEN-LAST:event_btn_enamActionPerformed

    private void btn_limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limaActionPerformed
        // TODO add your handling code here:
        tambahAngka("5");
    }//GEN-LAST:event_btn_limaActionPerformed

    private void btn_empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empatActionPerformed
        // TODO add your handling code here:
        tambahAngka("4");
    }//GEN-LAST:event_btn_empatActionPerformed

    private void btn_delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delapanActionPerformed
        // TODO add your handling code here:
        tambahAngka("8");

    }//GEN-LAST:event_btn_delapanActionPerformed

    private void btn_sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sembilanActionPerformed
        // TODO add your handling code here:
        tambahAngka("9");
    }//GEN-LAST:event_btn_sembilanActionPerformed

    private void btn_tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tujuhActionPerformed
        // TODO add your handling code here:
        tambahAngka("7");
    }//GEN-LAST:event_btn_tujuhActionPerformed

    private void btn_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaliActionPerformed
        // TODO add your handling code here:
        setOperasi("*");

    }//GEN-LAST:event_btn_kaliActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        setOperasi("+");

    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bagiActionPerformed
        // TODO add your handling code here:
        setOperasi("/");

    }//GEN-LAST:event_btn_bagiActionPerformed

    private void btn_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kurangActionPerformed
        // TODO add your handling code here:
        setOperasi("-");

    }//GEN-LAST:event_btn_kurangActionPerformed

    private void btn_komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_komaActionPerformed
        // TODO add your handling code here:
        String teks = jLabel2.getText();
        if (!teks.contains(".")) {
            jLabel2.setText(teks + ".");
        }
    }//GEN-LAST:event_btn_komaActionPerformed

    private void btn_samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_samadenganActionPerformed
        // TODO add your handling code here:
        String teks = jLabel2.getText();
        if (!teks.isEmpty()) {
            double angka = Double.parseDouble(teks);
            hitung(angka);
            operasi = "";
            baru = true;
        }
    }//GEN-LAST:event_btn_samadenganActionPerformed

    private void btn_nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nolActionPerformed
        // TODO add your handling code here:
        tambahAngka("0");
    }//GEN-LAST:event_btn_nolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bagi;
    private javax.swing.JButton btn_delapan;
    private javax.swing.JButton btn_dua;
    private javax.swing.JButton btn_empat;
    private javax.swing.JButton btn_enam;
    private javax.swing.JButton btn_kali;
    private javax.swing.JButton btn_koma;
    private javax.swing.JButton btn_kurang;
    private javax.swing.JButton btn_lima;
    private javax.swing.JButton btn_menjadikan_plus_atau_minus;
    private javax.swing.JButton btn_nol;
    private javax.swing.JButton btn_persen;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_samadengan;
    private javax.swing.JButton btn_satu;
    private javax.swing.JButton btn_sembilan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tiga;
    private javax.swing.JButton btn_tujuh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private void tambahAngka(String angka) {
        if (baru) {
            jLabel2.setText("");
            baru = false;
        }
        jLabel2.setText(jLabel2.getText() + angka);
    }

    private void setOperasi(String op) {
        String teks = jLabel2.getText();
        if (!teks.isEmpty()) {
            double angka = Double.parseDouble(teks);
            if (!operasi.isEmpty()) {
                hitung(angka);
            } else {
                hasil = angka;
            }
            operasi = op;
            baru = true;
        }
    }

    private void hitung(double angka) {
        switch (operasi) {
            case "+":
                hasil += angka;
                break;
            case "-":
                hasil -= angka;
                break;
            case "*":
                hasil *= angka;
                break;
            case "/":
                if (angka != 0) {
                    hasil /= angka;
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Tidak bisa dibagi dengan nol", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
        jLabel2.setText(String.valueOf(hasil));
    }
}
